export const COMPANY_TYPE_DICT = [
    {label: "Transporteur", value: "carrier"},
    {label: "Donneur d'ordre", value: "shipper"},
    {label: "Groupement", value: "group"},
    {label: "Commissionnaire", value: "broker"},
    {label: "Expéditeur ou Destinataire", value: "sender_or_consignee"},
    {label: "Stockage", value: "storage"},
    {label: "Conseil", value: "consulting"},
    {label: "Éditeur logiciel", value: "software_editor"},
    {label: "Formation", value: "training"},
    {label: "Autre", value: "other"},
];

export const BUSINESS_SECTOR_DICT = [
    {label: "Agro-Alimentaire (Cereales)", value: "agricultural_bulk"},
    {label: "Travaux Publics", value: "export construction_publics"},
    {label: "Industriel", value: "industry"},
    {label: "Déchets", value: "waste_management"},
    {label: "Bois", value: "wood"},
    {label: "Qualimat", value: "gmp_qualimat"},
    {label: "Grande distribution (Generale)", value: "retail"},
    {label: "Véhicules", value: "vehicles"},
    {label: "Animaux", value: "animals"},
    {label: "Messagerie", value: "parcel"},
    {label: "Carburant (ADR)", value: "dangerous_goods"},
    {label: "Déménagement", value: "moving"},
    {label: "Convoyage", value: "conveying"},
    {label: "Container", value: "container"},
    {label: "Frigorifique", value: "frigorific"},
    {label: "Palettes", value: "pallets"},
    {label: "Express", value: "Express"},
    {
        label: "Location véhicule avec chauffeur",
        value: "rental_with_drivers",
    },
    {label: "Convoi Exceptionnel", value: "special_convoy"},
    {label: "Traction", value: "traction"},
    {label: "Vrac solide", value: "dry_bulk"},
    {label: "Vrac liquide", value: "liquid_bulk"},
    {label: "Lots complets / partiels", value: "full_partial_lots"},
    {label: "Grue / levage", value: "crane_lifting"},
    {label: "Transport de Voyageurs", value: "passengers_transport"},
    {label: "Médical", value: "medical"},
    {
        label: "LDD Livraison Direct à Domicile",
        value: "direct_home_delivery",
    },
    {
        label: "Distribution petits commerces",
        value: "distribution_small_business",
    },
    {label: "Événementiel", value: "events"},
    {label: "Luxe/Art", value: "luxury_arts"},
    {
        label: "Inconnu à ce stade (⚠️à mettre à jour à posteriori)",
        value: "unknown",
    },
    {label: "Carrière", value: "stone_quary"},
    {label: "export Construction", value: "export construction_btp"},
    {label: "Environnement", value: "environment"},
    {label: "Méthanisation", value: "methanisation"},
    {
        label: "Location matériel BTP",
        value: "export construction_material_rental",
    },
    {label: "Prefabrique beton", value: "prefab_concrete"},
    {label: "Equipement industriel", value: "industrial_equipment"},
    {label: "Montage echaffaudage", value: "scaffold"},
    {
        label: "Transport of machinery | Tpt d'engins",
        value: "transport_of_machinery",
    },
];
export const TMS_DICT = [
    {label: "Aucun TMS", value: "no_tms"},
    {label: "ACS Trans (Cofisoft)", value: "acs_trans"},
    {label: "Advantage (Sigma)", value: "advantage_sigma"},
    {label: "AIDA Transports", value: "aida_transports"},
    {label: "Akanea Start", value: "akanea_start"},
    {label: "Akanea Suite", value: "akanea_suite"},
    {label: "Alpega TMS (BE)", value: "alpega_tms"},
    {label: "Andsoft", value: "andsoft"},
    {label: "Antsroute", value: "antsroute"},
    {label: "Beclyff", value: "beclyff"},
    {label: "Bluejay (BE)", value: "bluejay"},
    {label: "Cargo TMS (Dornach)", value: "qargo_tms_dornach"},
    {label: "Carlo (Soloplan)", value: "carlo_soloplan"},
    {label: "CJM (Cofisoft)", value: "cjm"},
    {label: "D'Artagnan (GPI)", value: "d_artagnan_gpi"},
    {label: "Dashdoc", value: "dashdoc"},
    {label: "Dispatch", value: "dispatch"},
    {label: "DSTI - Puissance i", value: "dsti_puissance_i"},
    {label: "Eurotracs (BE)", value: "eurotracs"},
    {label: "Generix", value: "generix"},
    {label: "Hardis", value: "hardis"},
    {label: "HUB ONE", value: "hub_one"},
    {label: "Infovisa - Transmagic", value: "infovisa_transmagic"},
    {label: "IT2000", value: "it2000"},
    {label: "ITEM Exellium", value: "item_exellium"},
    {label: "ITEM Trans", value: "item_trans"},
    {label: "KPA6T", value: "kpa6t"},
    {label: "Logimatique", value: "logimatique"},
    {label: "Mauchamp", value: "mauchamp"},
    {label: "Navitrans", value: "navitrans"},
    {label: "Nessy (editeur Caktus)", value: "nessy_editeur_caktus"},
    {label: "Odoo", value: "odoo"},
    {label: "OMP", value: "omp"},
    {label: "PARC (Plein Axe)", value: "parc_plein_axe"},
    {label: "Road Manager", value: "road_manager"},
    {label: "Safari GT (déménagement)", value: "safari_gt"},
    {label: "SAP", value: "sap"},
    {label: "Shiptify", value: "shiptify"},
    {label: "SMS (Viewtrans)", value: "sms_viewtrans"},
    {label: "StoreWay (Puissance i)", value: "storeway_puissance_i"},
    {label: "Strada", value: "strada"},
    {label: "Städtler Logistik", value: "städtler_logistik"},
    {label: "Syslog", value: "syslog"},
    {label: "Systrans", value: "systrans"},
    {label: "TAS", value: "tas"},
    {
        label: "Techni-Trans (Technisoft)",
        value: "techni_trans_technisoft",
    },
    {label: "Teliae", value: "teliae"},
    {label: "TMS Maison", value: "home_tms"},
    {label: "TP Planning", value: "tp_planning"},
    {
        label: "TP5G (LC Informatique & Développement)",
        value: "tp5g_lc_informatique_developpement",
    },
    {label: "TPM (Codris)", value: "tpm_codris"},
    {label: "TraLyX", value: "tralyx"},
    {label: "Transline (BE)", value: "transline"},
    {label: "Transoft (IG Soft)", value: "transoft_ig_soft"},
    {label: "Transpas (NL)", value: "transpas"},
    {label: "Transporeon", value: "transporeon"},
    {label: "Traplus (A Plus Informatique)", value: "traplus"},
    {label: "Urbantz (BE)", value: "urbantz"},
    {label: "Vialtic", value: "vialtic"},
    {label: "Win TP(Wininfo)", value: "win_tp_wininfo"},
    {label: "Winsped (LIS)", value: "winsped_lis"},
    {label: "Wintrans (Urios)", value: "wintrans_urios"},
    {label: "Wintruck", value: "wintruck"},
    {label: "Xyric (Proxylog)", value: "xyric_proxylog"},
    {label: "Autre", value: "other"},
    {label: "Winfret (Abacom)", value: "winfret_abacom"},
];

export const INVOICING_TOOL_DICT = [
    {label: "Quickbooks", value: "quickbooks"},
    {label: "TP5G (LC Informatique & Développement)", value: "tp5g"},
    {label: "ACS Trans (Cofisoft)", value: "acs_trans_cofisoft"},
    {label: "Akanea", value: "akanea"},
    {label: "Andsoft", value: "andsoft"},
    {label: "Artinove", value: "artinove"},
    {label: "Aucun", value: "no_tool"},
    {label: "Axonaut", value: "axonaut"},
    {label: "Beclyff", value: "beclyff"},
    {label: "Carlo (Soloplan)", value: "carlo_soloplan"},
    {label: "Cegid Quadra", value: "cegid_quadra"},
    {label: "Cogilog", value: "cogilog"},
    {label: "ComptAÉ", value: "comptae"},
    {label: "Debitoor", value: "debitoor"},
    {label: "EasyInvoice", value: "easyinvoice"},
    {label: "EBP", value: "ebp"},
    {label: "Eco Rec", value: "eco_rec"},
    {label: "Evoliz", value: "evoliz"},
    {label: "Excel", value: "excel"},
    {label: "Facturation pro", value: "facturation_pro"},
    {label: "Free Devis", value: "free_devis"},
    {label: "Gestan", value: "gestan"},
    {label: "GPI", value: "gpi"},
    {label: "Henrri", value: "henrri"},
    {label: "Invoice2go", value: "invoice2go"},
    {label: "Isafac", value: "isafac"},
    {label: "Isagri", value: "isagri"},
    {label: "Item", value: "item"},
    {label: "ITEM TRANS", value: "item_trans"},
    {label: "KeoBiz", value: "keobiz"},
    {label: "Koalaboox", value: "koalaboox"},
    {label: "LegalStart", value: "legal_start"},
    {label: "LIS", value: "lis"},
    {label: "Logiciel maison", value: "home_software"},
    {label: "Mon Expert en Gestion (MEG)", value: "mon_expert_gestion"},
    {label: "OMP", value: "omp"},
    {label: "Oxygene", value: "oxygene"},
    {label: "PARC (Plein Axe)", value: "parc_plein_axe"},
    {label: "QuadraFact", value: "quadrafact"},
    {label: "Sage 100cloud", value: "sage_100cloud"},
    {label: "Quickbooks", value: "quickbooks"},
    {label: "Sage 50cloud Ciel", value: "sage_50cloud_ciel"},
    {label: "Sage Apinégoce", value: "sage_pinégoce"},
    {
        label: "Sage Business Cloud Compta & Facturation",
        value: "sage_business_cloud_compta_facturation",
    },
    {label: "Sellsy", value: "sellsy"},
    {label: "Strada", value: "strada"},
    {
        label: "Techni-Trans (Technisoft)",
        value: "techni_trans_technisoft",
    },
    {label: "Tiime", value: "tiime"},
    {label: "TowSoft", value: "tow_soft"},
    {label: "TPM (Codris)", value: "tpm_codris"},
    {label: "Vialtic", value: "vialtic"},
    {label: "VosFactures", value: "vos_factures"},
    {label: "Wintrans (Urios)", value: "wintrans_urios"},
    {label: "Wintruck", value: "wintruck"},
    {label: "Xyric", value: "xyric"},
    {label: "Zervant", value: "zervant"},
    {label: "iSuite", value: "isuite"},
    {label: "Winbooks", value: "winbooks"},
    {label: "Teogest", value: "teogest"},
    {label: "Billit", value: "billit"},
];

export const TELEMATIC_TOOL_DICT = [
    {label: "Aucun", value: "no_telematic"},
    {label: "Addsecure ( ex-Vehco)", value: "addsecure"},
    {label: "Alertgasoil", value: "alertgasoil"},
    {label: "Anstroute", value: "anstroute"},
    {label: "AS 24", value: "as_24"},
    {label: "Astrata", value: "astrata"},
    {label: "Axxès Fleet Manager", value: "axxes_fleet_manager"},
    {label: "BlueTree", value: "blue_tree"},
    {label: "CargoFleet (Idem Telematics)", value: "cargo_fleet"},
    {label: "DAF connect", value: "daf_connect"},
    {label: "Dynafleet Volvo", value: "dynafleet_volvo"},
    {label: "Eliott", value: "eliott"},
    {label: "Fleetboard Mercedes", value: "fleetboard_mercedes"},
    {label: "Fleetmatics", value: "fleetmatics"},
    {label: "Frotcom", value: "frotcom"},
    {label: "Geoclic Solutions", value: "geoclic_solutions"},
    {label: "Geoloc Systems", value: "geoloc_systems"},
    {label: "GeoTracer", value: "geo_tracer"},
    {label: "Greencat", value: "greencat"},
    {label: "Keeptrace", value: "keeptrace"},
    {label: "Koovea", value: "koovea"},
    {label: "Lupa", value: "lupa"},
    {label: "Map and truck", value: "map_and_truck"},
    {label: "Mapon", value: "mapon"},
    {label: "MappingControl", value: "mapping_control"},
    {label: "Masternaut", value: "masternaut"},
    {label: "Masternaut SAS Web", value: "masternautsasweb"},
    {label: "Nomattitude", value: "nomattitude"},
    {label: "Ocean", value: "ocean"},
    {label: "ooclock", value: "ooclock"},
    {label: "Optifleet (Renault)", value: "optifleet"},
    {label: "Orange business (ex Ocean)", value: "orange_business"},
    {label: "Plusieurs export constructeurs", value: "severals_export constructors"},
    {label: "Quartix", value: "quartix"},
    {label: "Rio MAN", value: "rio_man"},
    {label: "Scania Fleet", value: "scania_fleet"},
    {label: "Situaction", value: "situaction"},
    {label: "Strada", value: "strada"},
    {label: "Tracar", value: "tracar"},
    {label: "Tracksolid", value: "tracksolid"},
    {label: "Trackunit", value: "trackunit"},
    {label: "Transics", value: "transics"},
    {label: "Traqueur (Coyote)", value: "traqueur"},
    {label: "Trimble", value: "trimble"},
    {label: "Truckonline", value: "truckonline"},
    {label: "Vehizen", value: "vehizen"},
    {label: "Verizon Connect", value: "verizon_connect"},
    {label: "Volvo connect", value: "volvo_connect"},
    {label: "Wayzz", value: "wayzz"},
    {label: "WebEye", value: "webeye"},
    {label: "Webfleet (ex TomTom)", value: "webfleet"},
    {label: "Wialon", value: "wialon"},
    {label: "Autre", value: "other"},
    {label: "Sud Télématique", value: "sud_télématique"},
    {label: "Radius telematics", value: "radius_telematics"},
    {label: "Hermes", value: "hermes"},
    {label: "Pass Traçabilité", value: "pass_tracabilite"},
    {label: "BizzTrack", value: "bizztrack"},
];
export const TRUCK_TYPE_DICT = [
    {label: "ADR", value: "dangerous_goods"},
    {label: "Benne", value: "dump_truck"},
    {label: "Citerne liquide", value: "liquid_tanker"},
    {label: "Citerne pulvérulente", value: "powder_tanker"},
    {label: "Convoi exceptionnel", value: "special_convoy"},
    {label: "FMA", value: "mooving_floor_trailer"},
    {label: "VL (Véhicule léger)", value: "light_vehicle"},
    {label: "Grue / Levage", value: "crane_lifting"},
    {label: "Plateau", value: "flatbed_truck"},
    {label: "Porte-char", value: "tank_carrier"},
    {label: "Porte-conteneur", value: "container_carrier"},
    {label: "Porte-voiture", value: "vehicule_carrying_truck"},
    {label: "Porteur avec hayon", value: "truck_with_tailgate"},
    {label: "Tautliner", value: "tautliner"},
    {label: "Température dirigée", value: "controlled_temperature"},
    {label: "Toupie", value: "mixer_truck"},
    {label: "Grumier", value: "lopping_truck"},
    {label: "Bétaillère", value: "livestock_truck"},
    {label: "Ampliroll", value: "ampliroll"},
    {label: "Autre", value: "other"},
];
export const LEAD_STATUS_DICT = [
    {label: "❄ Lead New", value: "lead_new"},
    {label: "📞Lead ongoing", value: "lead_ongoing"},
    {label: "🚗 Lead to visit", value: "lead_to_visit"},
    {label: "⭐MQL New", value: "mql_new"},
    {label: "📞MQL Ongoing", value: "mql_ongoing"},
    {label: "🔥 SQL", value: "sql"},
    {label: "⛔ Bad timing", value: "bad_timing"},
    {label: "⛔ Not ICP", value: "not_icp"},
    {label: "⛔ Bad data", value: "bad_data"},
    {label: "⛔ Not a lead", value: "not_a_lead"},
    {label: "⛔ Subsidiary | decision by HQ", value: "subsidiary"},
    {label: "📵 NRP | does not answer", value: "does_not_answer"},
    {label: "💌 Invitee", value: "invitee"},
    {label: "🕵Competitor", value: "competitor"},
    {label: "🎈 Partner", value: "partner"},
    {label: "💎 Opportunity", value: "opportunity"},
    {label: "🤝 Customer", value: "customer"},
    {label: "👎 Deal lost", value: "deal_lost"},
    {label: "😢 Churn at renewal", value: "churn_or_renewal"},
    {label: "😢 Churn during OB", value: "churn_during_ob"},
    {label: "✅ Customer OB", value: "customer_ob"},
    {label: "✅ Customer Ramp-up", value: "customer_ramp_up"},
    {label: "✅ Customer Run", value: "customer_run"},
    {label: "🔍 Unfound Phone number", value: "unfounded_phone"},
    {label: "💻 User", value: "computer_user"},
    {label: "🐜Very small carrier", value: "very_small_carrier"},
    {label: "🔄Transport=secondary activity", value: "secondary_transportation_activity"},
    {label: "👩‍🎓 Students ambassador", value: "students_ambassador"},
    {label: "🚚 Chartered journey", value: "chartered_journey"},
];

export const CRM_OWNER_DICT = [
    {label: "Alix de Montcheuil", value: "139699863"},
    {label: "Amin Harmak", value: "236644757"},
    {label: "Amélie Vilsalmon", value: "118017603"},
    {label: "Anush Polfliet", value: "303998008"},
    {label: "Antoine Couronné", value: "108134984"},
    {label: "Antonin Mansour", value: "227057052"},
    {label: "Arthur Lejeune", value: "380142100"},
    {label: "Arthur Ouaki", value: "108134978"},
    {label: "Camille Hibon", value: "230930025"},
    {label: "Clémence Levieil", value: "166986576"},
    {label: "Corentin Smith", value: "116014382"},
    {label: "Davy Beersaerts", value: "147177552"},
    {label: "Elien Vanderborcht", value: "179822772"},
    {label: "Elisabeth BONCLER", value: "128897658"},
    {label: "Fabien Poulard", value: "108134680"},
    {label: "Frédéric DE FOUCAULT", value: "223938061"},
    {label: "Gontran Filandre", value: "147563577"},
    {label: "Gustave Billaudel", value: "113588380"},
    {label: "Guillemette de Malglaive", value: "151351855"},
    {label: "Gustave Billaudel", value: "113588380"},
    {label: "Hélène Delaporte", value: "108134986"},
    {label: "Hélène Gélin", value: "108134983"},
    {label: "Hugues Fournial", value: "240934237"},
    {label: "Jimmy Perret", value: "108134972"},
    // fusion with  {label: "Sarah GOFFIN", value: "223934260"},
    {label: "Jordan Martinel", value: "920448349,223934260"},
    {label: "Kawtar Sabri", value: "263653176"},
    {label: "Laura Nakach", value: "137422384"},
    {label: "Laura Rincon", value: "549764792"},
    {label: "Laura Silva", value: "139599011"},
    // fusion with   {label: "Guillaume COCHOIS", value: "102030129"},
    {label: "Lucas Estardier", value: "249488906,102030129"},
    {label: "Louis Gachet", value: "179826720"},
    {label: "Imad AMHAL", value: "118017601"},
    // fusion with   {label: "Imad AMHAL", value: "118017601"},
    {label: "Madeg Moulines", value: "223938066,118017601"},
    {label: "Marie Vivier", value: "729012823"},
    {label: "Marine Georget", value: "126816682"},
    {label: "Marion Rousseau", value: "108134982"},
    {label: "Mathieu JOUANGUY", value: "108134987"},
    {label: "Myriam Roué", value: "278986335"},
    // fusion with   {label: "Samuel Tessier", value: "189798166"},
    {label: "Nathan PAUCTON", value: "108134975,189798166"},
    {label: "Nikita Kirilovs", value: "236663454"},
    {label: "Pascal Ehlen", value: "155597384"},
    {label: "Paul-Hubert des Minières", value: "58046855"},
    {label: "Penny Appelman", value: "278465632"},
    {label: "Philippine Thomas", value: "108134974"},
    {label: "Pierre-Olivier d'Audiffret", value: "108134976"},
    {label: "Raphaëlle Coutolleau", value: "108134980"},
    {label: "Rashied Nanhekhan", value: "236645488"},
    {label: "Rohann Koutélé", value: "119041090"},
    // fusion with   {label: "Adrien Oblin", value: "203547675"},
    {label: "Sami Dandache", value: "126896009,203547675"},
    {label: "Sofie Hale", value: "2008439219"},
    {label: "Sophie de Bressy", value: "137421067"},
    {label: "Sophie de Mercey", value: "108134979"},
    {label: "Stéphane Souêtre", value: "108134981"},
    // fusion with   {label: "Sonia Veyrat", value: "239341617"},
    {label: "Thomas Boudaud", value: "1432838636,239341617"},
    {label: "Valentin QUERE", value: "118017602"},
    {label: "Victor Billaud", value: "258482788"},
    {label: "Zoe MERLIN", value: "137422382"},
    {label: "Unknown", value: "unknown"},
];

export const DASHDOC_ACCOUNT_TYPE = [
    {label: "Customer", value: "subscribed"},
    {label: "Registered", value: "has_loggable_managers"},
];
