// This file was generated by api-spec/openapi_to_ts.py. Do not edit it manually.

import * as z from "zod";

// @ts-ignore
import * as DynamicForm from "./DynamicForm";
// @ts-ignore
import * as Extensions from "./Extensions";

export type TripSendToNetwork = {
    trigger: "trip_send_to_network";
    extension: Extensions.ShortExtension;
};
export const TripSendToNetworkSchema = z.object({
    trigger: z.enum(["trip_send_to_network"]),
    extension: Extensions.ShortExtensionSchema,
});

export type AccountTriggersResponse = {
    triggers: TripSendToNetwork[];
};
export const AccountTriggersResponseSchema = z.object({
    triggers: z.array(TripSendToNetworkSchema),
});
