import {
    TransportsAndOrdersSettings,
    TransportsSettings,
    TransportsToInvoiceSettings,
    TransportsToInvoiceSettingsSchema,
} from "app/features/transport/transports-list/transportsSettingsView.types";

export const DEFAULT_TRANSPORTS_SETTINGS: TransportsSettings = {
    period: undefined,
    start_date: undefined,
    end_date: undefined,
    loading_period: undefined,
    loading_start_date: undefined,
    loading_end_date: undefined,
    unloading_period: undefined,
    unloading_start_date: undefined,
    unloading_end_date: undefined,
    text: [],
    tags__in: [],
    shipper__in: [],
    parent_shipper__in: [],
    carrier__in: [],
    subcontracted_carrier__in: [],
    creator__in: [],
    trucker__in: [],
    address__in: [],
    origin_address__in: [],
    destination_address__in: [],
    invoicing_status__in: [],
    transport_status__in: [],
    order_status__in: [],
    address_text: "",
    address_postcode__in: "",
    address_country__in: "",
    origin_address_text: "",
    origin_address_postcode__in: "",
    origin_address_country__in: "",
    destination_address_text: "",
    destination_address_postcode__in: "",
    destination_address_country__in: "",
    subcontracted_transports: undefined,
    has_price: undefined,
    has_carbon_footprint: undefined,
    has_booking_needed: undefined,
    has_cmr_to_be_checked: undefined,
    has_complete_cmr_document: undefined,
    has_non_cmr_document: undefined,
    has_observations: undefined,
    has_weight_to_be_checked: undefined,
    has_customer_to_invoice: undefined,
    has_missing_invoice_item: undefined,
    has_edition_by_trucker: undefined,
    loading_duration__lte: undefined,
    loading_duration__gt: undefined,
    unloading_duration__lte: undefined,
    unloading_duration__gt: undefined,
    origin_arrival_delay__lte: undefined,
    origin_arrival_delay__gt: undefined,
    destination_arrival_delay__lte: undefined,
    destination_arrival_delay__gt: undefined,
    destination_arrival_delay: undefined,
    origin_arrival_delay: undefined,
    cancelled: undefined,
    is_done: undefined,
    is_order: undefined,
    is_child: undefined,
    duration_on_site__gte: undefined,
};
export const DEFAULT_TRANSPORTS_AND_ORDERS_SETTINGS: TransportsAndOrdersSettings = {
    ...DEFAULT_TRANSPORTS_SETTINGS,
    archived: undefined,
};
export const DEFAULT_TRANSPORTS_DASHBOARD_SETTINGS: TransportsAndOrdersSettings = {
    ...DEFAULT_TRANSPORTS_SETTINGS,
    archived: false,
};
export const DEFAULT_TRANSPORTS_TO_INVOICE_SETTINGS: TransportsToInvoiceSettings = {
    ...TransportsToInvoiceSettingsSchema.parse(DEFAULT_TRANSPORTS_SETTINGS),
    archived: false,
    debtor__in: [],
    created_period: undefined,
    created_start_date: undefined,
    created_end_date: undefined,
};
