import {t} from "@dashdoc/web-core";
import {Trailer, TransportAddress, Trucker, Vehicle} from "dashdoc-utils";

import {CompactTrip} from "app/features/trip/trip.types";

export function getFakeTrip(): CompactTrip {
    return {
        uid: "fake-card-uid",
        created: "2022-06-03T12:00:00Z",
        name: t("trip.nameInput"),
        trucker: {
            pk: 1,
            display_name: t("scheduler.cardSettings.display_trucker"),
        } as Trucker,
        vehicle: {
            license_plate: "001VEH55",
            fleet_number: "PARC1",
        } as Vehicle,
        trailer: {
            license_plate: "001TRA55",
            fleet_number: "TRPARC1",
        } as Trailer,
        activities: [
            {
                uid: "origin-id",
                address: {
                    pk: 1,
                    original: 2,
                    name: "origin name",
                    address: "origin address",
                    city: "Nantes",
                    postcode: "44000",
                    country: "FR",
                } as TransportAddress,
                status: "activity_done",
                real_start: "2022-06-03T08:00:00Z",
                real_end: "2022-06-03T08:00:00Z",
                slots: [{start: "2022-06-03T08:00:00Z", end: "2022-06-03T08:00:00Z"}],
                eta: "",
                eta_tracking: false,
                reference: "origin_ref",
                punctuality_status: "untracked",
                category: "loading",
                deliveries_from: [],
                deliveries_to: [],
                transports: [
                    {
                        sequential_id: 1234,
                        id: 1,
                        uid: "12345",
                        shipper: {
                            name: t("scheduler.cardSettings.shipper_name"),
                        },

                        requested_vehicle: {
                            group_view_id: 1,
                            label: "grain_dump",
                            complementary_information: "",
                            uid: "123",
                            emission_rate: 0.086,
                            generic_emission_rate_uid: null,
                            default_for_carbon_footprint: false,
                        },
                        tags: [
                            {
                                pk: 1,
                                name: t("common.tag") + " 1",
                                color: "#4B71FA",
                            },
                            {
                                pk: 2,
                                name: t("common.tag") + " 2",
                                color: "#8FD458",
                            },
                            {
                                pk: 3,
                                name: t("common.tag") + " 3",
                                color: "#F0619D",
                            },
                            {
                                pk: 4,
                                name: t("common.tag") + " 4",
                                color: "#E54D45",
                            },
                        ],
                        instructions: t("transportForm.globalInstructionsTitle"),
                        is_order: false,
                        requires_acceptance: false,
                        global_status: "ongoing",
                        invoicing_status: "UNVERIFIED",
                        business_privacy: false,
                        is_multiple_compartments: false,
                        carrier_id: 1,
                        deleted: null,
                        shipper_reference: "shipper_ref",
                        carrier_reference: "carrier_ref",
                    },
                ],
                fakeMerged: false,
                similarUids: [],
                cancelled_status: null,
            },
            {
                uid: "destaination-id-1",
                address: {
                    pk: 1,
                    original: 2,
                    name: "destination 1 name",
                    address: "destination 1 address",
                    city: "Brest",
                    postcode: "29200",
                    country: "FR",
                } as TransportAddress,
                status: "on_site",
                real_start: "2022-06-03T09:00:00Z",
                real_end: null,
                slots: [{start: "2022-06-03T09:00:00Z", end: "2022-06-03T09:00:00Z"}],
                eta: "",
                eta_tracking: false,
                reference: "",
                punctuality_status: "untracked",
                deliveries_from: [],
                deliveries_to: [],
                category: "unloading",
                transports: [
                    {
                        sequential_id: 1234,
                        id: 1,
                        uid: "12345",
                        shipper: {
                            name: t("scheduler.cardSettings.shipper_name"),
                        },

                        requested_vehicle: {
                            group_view_id: 1,
                            label: "grain_dump",
                            complementary_information: "",
                            uid: "123",
                            emission_rate: 0.086,
                            generic_emission_rate_uid: null,
                            default_for_carbon_footprint: false,
                        },
                        tags: [
                            {
                                pk: 1,
                                name: t("common.tag") + " 1",
                                color: "#4B71FA",
                            },
                            {
                                pk: 2,
                                name: t("common.tag") + " 2",
                                color: "#8FD458",
                            },
                            {
                                pk: 3,
                                name: t("common.tag") + " 3",
                                color: "#F0619D",
                            },
                            {
                                pk: 4,
                                name: t("common.tag") + " 4",
                                color: "#E54D45",
                            },
                        ],
                        instructions: t("transportForm.globalInstructionsTitle"),
                        is_order: false,
                        requires_acceptance: false,
                        global_status: "ongoing",
                        invoicing_status: "UNVERIFIED",
                        business_privacy: false,
                        is_multiple_compartments: false,
                        carrier_id: 1,
                        deleted: null,
                        shipper_reference: "shipper_ref",
                        carrier_reference: "carrier_ref",
                    },
                ],
                fakeMerged: false,
                similarUids: [],
                cancelled_status: null,
            },
            {
                uid: "destination-id-2",
                address: {
                    pk: 1,
                    original: 2,
                    name: "destination 2 name",
                    address: "destination 2 address",
                    city: "Paris",
                    postcode: "75000",
                    country: "FR",
                } as TransportAddress,
                status: "created",
                real_start: null,
                real_end: null,
                slots: [{start: "2022-06-03T10:00:00Z", end: "2022-06-03T12:00:00Z"}],
                eta: "",
                eta_tracking: false,
                reference: "",
                punctuality_status: "untracked",
                category: "unloading",
                deliveries_from: [],
                deliveries_to: [],
                transports: [
                    {
                        sequential_id: 1234,
                        id: 1,
                        uid: "12345",
                        shipper: {
                            name: t("scheduler.cardSettings.shipper_name"),
                        },

                        requested_vehicle: {
                            group_view_id: 1,
                            label: "grain_dump",
                            complementary_information: "",
                            uid: "123",
                            emission_rate: 0.086,
                            generic_emission_rate_uid: null,
                            default_for_carbon_footprint: false,
                        },
                        tags: [
                            {
                                pk: 1,
                                name: t("common.tag") + " 1",
                                color: "#4B71FA",
                            },
                            {
                                pk: 2,
                                name: t("common.tag") + " 2",
                                color: "#8FD458",
                            },
                            {
                                pk: 3,
                                name: t("common.tag") + " 3",
                                color: "#F0619D",
                            },
                            {
                                pk: 4,
                                name: t("common.tag") + " 4",
                                color: "#E54D45",
                            },
                        ],
                        instructions: t("transportForm.globalInstructionsTitle"),
                        is_order: false,
                        requires_acceptance: false,
                        global_status: "ongoing",
                        invoicing_status: "UNVERIFIED",
                        business_privacy: false,
                        is_multiple_compartments: false,
                        carrier_id: 1,
                        deleted: null,
                        shipper_reference: "shipper_ref",
                        carrier_reference: "carrier_ref",
                    },
                ],
                fakeMerged: false,
                similarUids: [],
                cancelled_status: null,
            },
            {
                uid: "break-id",
                address: {
                    pk: 1,
                    original: 2,
                    name: "break name",
                    address: "break address",
                    city: "Lyon",
                    postcode: "69000",
                    country: "FR",
                } as TransportAddress,
                status: "created",
                real_start: null,
                real_end: null,
                slots: [{start: "2022-06-03T13:00:00Z", end: "2022-06-03T14:00:00Z"}],
                eta: "",
                eta_tracking: false,
                reference: "",
                punctuality_status: "untracked",
                category: "breaking",
                deliveries_from: [],
                deliveries_to: [],
                transports: [
                    {
                        sequential_id: 1234,
                        id: 1,
                        uid: "12345",
                        shipper: {
                            name: t("scheduler.cardSettings.shipper_name"),
                        },

                        requested_vehicle: {
                            group_view_id: 1,
                            label: "grain_dump",
                            complementary_information: "",
                            uid: "123",
                            emission_rate: 0.086,
                            generic_emission_rate_uid: null,
                            default_for_carbon_footprint: false,
                        },
                        tags: [
                            {
                                pk: 1,
                                name: t("common.tag") + " 1",
                                color: "#4B71FA",
                            },
                            {
                                pk: 2,
                                name: t("common.tag") + " 2",
                                color: "#8FD458",
                            },
                            {
                                pk: 3,
                                name: t("common.tag") + " 3",
                                color: "#F0619D",
                            },
                            {
                                pk: 4,
                                name: t("common.tag") + " 4",
                                color: "#E54D45",
                            },
                        ],
                        instructions: t("transportForm.globalInstructionsTitle"),
                        is_order: false,
                        requires_acceptance: false,
                        global_status: "ongoing",
                        invoicing_status: "UNVERIFIED",
                        business_privacy: false,
                        is_multiple_compartments: false,
                        carrier_id: 1,
                        deleted: null,
                        shipper_reference: "shipper_ref",
                        carrier_reference: "carrier_ref",
                    },
                ],
                fakeMerged: false,
                similarUids: [],
                cancelled_status: null,
            },
        ],
        scheduler_datetime_range: {start: "2022-06-03T08:00:00Z", end: "2022-06-03T14:00:00Z"},
        scheduled_order: 1,
        owned_by_company: true,
        is_prepared: true,
        status: "ongoing",
        inconsistentOrder: false,
        turnover: null,
        child_transport: null,
    };
}
