import {Company} from "dashdoc-utils";

import {Invoice} from "app/taxation/invoicing/types/invoice.types";

const companyA: Company = {
    pk: 344287,
    name: "Fab Carrier – Pays de Loire",
    group_view_id: 276416,
    managed_by_name: undefined,
    siren: "",
    country: "FR",
    account_type: "subscribed",
    notes: "",
};

export const invoice: Invoice = {
    __partial: false,
    uid: "f1289ac8-12d1-426a-b45e-6de82291fedd",
    is_bare_invoice: false,
    created_by: {
        pk: 344287,
        name: "Fab Carrier – Pays de Loire",
        primary_address: {
            pk: 6579124,
            name: "Fab Carrier",
            address: "Rue d'Erlon",
            city: "Nantes",
            postcode: "44000",
            country: "FR",
            latitude: 47.2186656,
            longitude: -1.5620563,
            radius: 500,
            coords_validated: false,
            is_carrier: true,
            is_shipper: true,
            is_origin: true,
            is_destination: false,
            created: "2020-03-05T10:14:02.108122Z",
            instructions: "",
            remote_id: "",
            company: companyA,
            flow_site: null,
        },
        country: "FR",
        vat_number: "FR28538296914",
        settings_logo: "",
    },
    document_number: "456874",
    status: "paid",
    debtor: {
        pk: 344269,
        name: "Fab Shipper",
        notes: "",
        primary_address: {
            pk: 6578958,
            name: "Fab Shipper",
            address: "Somewhere",
            city: "Over the rainbow",
            postcode: "12345",
            country: "FR",
            latitude: 46.227638,
            longitude: 2.213749,
            radius: 500,
            coords_validated: false,
            is_carrier: true,
            is_shipper: true,
            is_origin: false,
            is_destination: false,
            created: "2020-03-05T10:10:00.794490Z",
            instructions: "",
            remote_id: "",
            company: companyA,
            flow_site: null,
        },
        country: "FR",
        vat_number: "FR28538296914",
        invoicing_remote_id: "30943243029",
    },
    due_date: "2023-02-01",
    line_groups: [
        {
            id: 8513,
            transport: {
                uid: "1633624074200558OoZ4a2m",
                sequential_id: 3819917,
                deliveries: [
                    {
                        uid: "1633624074200558R0xKigf",
                        origin: {
                            company_name: "[Site] Delivery #1",
                            city: "Val-du-Layon",
                            uid: "1633624074200558JKbQfib",
                        },
                        destination: {company_name: "", city: "", uid: "1633624074200558fsOWYh0"},
                    },
                ],
                documents: [],
                messages: [
                    {
                        document:
                            "https://storage.googleapis.com/dashdoc-media/media/shipments/4c41071a-c6e9-44d4-8718-817d907047a1.jpeg",
                        reference: "",
                        document_type: "cmr",
                        author_company_id: 344287,
                        uid: "2b404692-37fc-4c1d-9b19-2332c44f869d",
                        extracted_reference: null,
                    },
                ],
            },
            lines: [
                {
                    id: 10348,
                    description: "Prix convenu",
                    quantity: "1.000",
                    unit_price: "149.000",
                    amount: "149.00",
                    currency: "EUR",
                    invoice_item: undefined,
                    is_gas_indexed: false,
                    tax_rate: "20.00",
                },
            ],
            total_price_without_tax: "149.00",
            description: "",
            ordering_datetime: "2021-10-14T13:05:47.641000Z",
            gas_index: "0.00",
            gas_index_invoice_item: null,
        },
        {
            id: 8518,
            transport: {
                uid: "8f15b312-d093-4ad0-83e8-49a0eb510300",
                sequential_id: 3826428,
                deliveries: [
                    {
                        uid: "6406a851-3777-42ad-b380-bd3b1072a0ab",
                        origin: {
                            company_name: "[Site] Pickup #1",
                            city: "Confolens",
                            uid: "16336970301395440ImUOS",
                        },
                        destination: {
                            company_name: "[Site] Delivery #2",
                            city: "Moulins-lès-Metz",
                            uid: "163369703013954nV98JmH",
                        },
                    },
                ],
                documents: [],
                messages: [
                    {
                        document:
                            "https://storage.googleapis.com/dashdoc-media/media/shipments/bb2686e5-2d91-4fee-874e-935a43d37fdd.pdf",
                        reference: "12355",
                        document_type: "cmr",
                        author_company_id: 344287,
                        uid: "8c46931b-007e-4d14-9253-d93133ed8832",
                        extracted_reference: null,
                    },
                ],
            },
            lines: [
                {
                    id: 10354,
                    description: "Prix convenu",
                    quantity: "1.000",
                    unit_price: "1009.000",
                    amount: "1009.00",
                    currency: "EUR",
                    invoice_item: undefined,
                    is_gas_indexed: false,
                    tax_rate: "20.00",
                },
            ],
            total_price_without_tax: "1009.00",
            description: "",
            ordering_datetime: "2021-10-14T13:14:28.234000Z",
            gas_index: "0.00",
            gas_index_invoice_item: null,
        },
        {
            id: 8514,
            transport: {
                uid: "1642436111158993kDyGo0g",
                sequential_id: 4603650,
                deliveries: [
                    {
                        uid: "1642436111158993Ce4tSio",
                        origin: {
                            company_name: "[Site] Pickup #1",
                            city: "Confolens",
                            uid: "1642436111158993G3cGvLs",
                        },
                        destination: {company_name: "", city: "", uid: "1642436111158993qUcVLLM"},
                    },
                ],
                documents: [
                    {
                        delivery: "1642436111158993Ce4tSio",
                        file: "https://www.dashdoc.eu/api/v4/delivery-documents/24124e65-26a0-4791-a64f-469384fed8f4/",
                        reference: "4568337",
                        category: "rental",
                    },
                ],
                messages: [],
            },
            lines: [
                {
                    id: 10349,
                    description: "Déplacement",
                    quantity: "1.000",
                    metric: "FLAT",
                    unit_price: "320.000",
                    amount: "320.00",
                    currency: "EUR",
                    invoice_item: undefined,
                    is_gas_indexed: false,
                    tax_rate: "20.00",
                    is_fuel_surcharge: false,
                },
            ],
            total_price_without_tax: "320.00",
            description: "",
            ordering_datetime: "2022-01-17T16:16:35.205000Z",
            gas_index: "0.00",
            gas_index_invoice_item: null,
        },
    ],
    currency: "EUR",
    created: "2022-03-14T16:29:35.080348Z",
    transports_count: 3,
    period: {
        first_loading_at: "2021-10-14T08:10:17.415000Z",
        last_unloading_at: "2022-03-14T11:41:00Z",
    },
    remote_id: "1469",
    invoicing_connector: {
        uid: "",
        category: "invoicing",
        data_source: "mock",
        parameters: {
            base_url: "https://example.com",
            realm_id: "9130347876593336",
            redirect_uri: "https://www.dashdoc.eu/app/settings/invoicing",
            french_standard_vat: {name: "20 % TVA FR", value: "7"},
            last_catalog_synchronization: "2022-05-20T08:51:38.683823+00:00",
        },
        pk: "524",
    },
    file: "https://storage.googleapis.com/dashdoc-media/media/invoices/8f050796-4b00-453e-9bcb-7597f64873b6.pdf",
    lines: [
        {
            id: 128450,
            description: "Transport",
            quantity: "1.000",
            unit_price: "20.000",
            amount: "20.00",
            currency: "EUR",
            invoice_item: undefined,
            is_gas_indexed: true,
            tax_rate: "20.00",
        },
        {
            id: 128451,
            description: "Transport",
            quantity: "1.000",
            unit_price: "20.000",
            amount: "20.00",
            currency: "EUR",
            invoice_item: undefined,
            is_gas_indexed: true,
            tax_rate: "20.00",
        },
    ],
    merge_by: "ALL_GROUPS",
    group_mode: "MERGED",
    invoicing_date: "2023-01-01",
    debtor_reference: "",
    free_text: "",
    show_carbon_footprint: true,
    total_carbon_footprint: null,
    number_of_transports_with_carbon_footprint: null,
    number_of_transports_without_carbon_footprint: null,
    description_template: null,
    total_price: "1518.00",
    communication_statuses: [],
    credit_notes: [],
    is_dashdoc: false,
    total_tax_amount: null,
    is_payment_late: false,
    attachments: [],
    bank_information: null,
    language: "fr",
    transports_groups_in_invoice: [],
    fuel_surcharge_in_footer: false,
    paid_at: null,
    payment_method: null,
    payment_notes: "",
};
