name: Build frontend images

on:
  workflow_call:
    inputs:
      run_if:
        type: boolean
        required: true

jobs:
  build:
    runs-on: runs-on,runner=4cpu-linux-x64,run-id=${{ github.run_id }}

    if: ${{ inputs.run_if }}

    timeout-minutes: 10

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          # By default, if the event that triggered the workflow is a pull_request event, the ref for the checkout action is the merge commit SHA. We want the actual commit SHA
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push frontend image
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: frontend/Dockerfile
          cache-from: type=s3,blobs_prefix=cache/docker-frontend,manifests_prefix=cache/docker-frontend,region=${{ env.RUNS_ON_AWS_REGION }},bucket=${{ env.RUNS_ON_S3_BUCKET_CACHE }}
          cache-to: type=s3,blobs_prefix=cache/docker-frontend,manifests_prefix=cache/docker-frontend,region=${{ env.RUNS_ON_AWS_REGION }},bucket=${{ env.RUNS_ON_S3_BUCKET_CACHE }},mode=max
          push: true
          tags: 654654565475.dkr.ecr.us-west-2.amazonaws.com/dashdoc-frontend-e2e-test:${{ github.sha }}
